### PR TITLE
[Refactor] Fix the padding and text size of the editor detail view by reflecting the hifi

### LINKED ISSUE #36: [Refactor] Fix the padding and text size of the editor detail view by reflecting the hifi.
# Structure
> Be specific and detailed so that your team members can understand. Please assign the person in charge as well.

- Current structure
   - Only the basic UI is drawn.

- Better structure
   - Fix the padding and text size of the editor detail view by reflecting the hifi.
   - Reflects the berry's hifi update.

- The size of the text changes according to the user's environment setting, and the design such as hifi follows.

### PR DESCRIPTION
**Pull request by rriver2**
# Issue Number
🔒 Close #36 

## Changes

- Changed files
Image (
campair/campair/Application/Assets.xcassets/FindingEquipmentIcon.imageset/Contents.json
campair/campair/Application/Assets.xcassets/FindingEquipmentIcon.imageset/FindingEquipment.svg
campair/campair/Application/Assets.xcassets/buttonArrow.imageset/Contents.json
campair/campair/Application/Assets.xcassets/buttonArrow.imageset/btn_arrow.svg
campair/campair/Application/Assets.xcassets/contentCard2.imageset/Contents.json
campair/campair/Application/Assets.xcassets/contentCard2.imageset/card_con.svg
"campair/campair/Application/Assets.xcassets/examplePainting.imageset/\354\212\244\355\201\254\353\246\260\354\203\267 2022-06-15 \354\230\244\355\233\204 5.27.39.png"
)
Entity (
campair/campair/Entity/OpeningSection.swift
)
Views(
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
campair/campair/View/Editor/Detail/OpeningEditorView.swift
campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
)
campair/campair/Application/ColorExtension.swift

## New features

- Added hex to Color function in ColorExtension
- Modified color properties to using Color extension
- Fix the padding and text size of the editor detail view by reflecting the hifi

## Questions

- Lining Space : The 42nd line OpeningEditorView (It says 26 in the sketch, but you have to take out the font size and calculate it. But I'm looking for an easy way. I set lineSpacing at 5 temporarily.)

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

### CODE REVIEW

File: campair/campair/Application/ColorExtension.swift [hunk 1]
```diff
@@ -8,12 +8,36 @@
 import SwiftUI
 
 extension Color {
-    static let customPaintingTextPink = Color(#colorLiteral(red: 0.9008693695, green: 0.5397311449, blue: 0.4869769216, alpha: 1))
-    static let customTextPink = Color(#colorLiteral(red: 0.9667707086, green: 0.6571794748, blue: 0.6073435545, alpha: 1))
-    static let customTextGray = Color(#colorLiteral(red: 0.576470077, green: 0.5764710903, blue: 0.5979604125, alpha: 1))
+    static let customBackGroundColor = Color(#colorLiteral(red: 0.9222490191, green: 0.8728070259, blue: 0.8261210322, alpha: 1))
```
Comment (unnnyong) [inline campair/campair/Application/ColorExtension.swift:11]: Color Assets을 사용하지 않는 이유가 궁금하무니다 ~

File: campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift [hunk 2]
```diff
@@ -18,9 +18,10 @@ struct EditorDetailContentsVersionView: View {
                     ForEach(equipmentContents.indices) { index in
                         let equipmentContent = equipmentContents[index]
                         EditorRecommendEquipmentView(equipmentContent: equipmentContent)
-                        Rectangle()
-                            .frame(height: 8)
-                            .foregroundColor(Color.customSectionGray)
+                        if index != equipmentContents.count-1 {
```
Comment (unnnyong) [inline campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift:21]: -1 은 어떤 의미인가요 ?  의미를 알기 쉽도록 정수로 표시해주면 나 ~~~~ 중의 유지보수에도 도움이 될듯해요

File: campair/campair/View/Editor/Detail/OpeningEditorView.swift [hunk 3]
```diff
@@ -12,32 +12,39 @@ struct OpeningEditorView: View {
...
+            VStack(alignment: .leading, spacing: 10) {
                 Text("\(self.openingSection.title)")
-                    .foregroundColor(Color.customTextPink)
+                    .foregroundColor(Color(hex: self.openingSection.cardTitleColor))
+                    .font(.system(.headline, design: .default))
                 Text("\(self.openingSection.subTitle)")
-                    .foregroundColor(Color.customTextGray)
+                    .foregroundColor(Color.customDarkGray)
+                    .font(.system(.body, design: .default))
+                // 스케치에서는 26으로 되어있는데 폰트 사이즈를 빼서 계산을 해야 한다고... but 쉬운 방법이 있을 거 같아서 찾아보는 중입니다.
```
Comment (unnnyong) [inline campair/campair/View/Editor/Detail/OpeningEditorView.swift:42]:
```suggestion
                // TODO: 스케치에서는 26으로 되어있는데 폰트 사이즈를 빼서 계산을 해야 한다고... but 쉬운 방법이 있을 거 같아서 찾아보는 중입니다.
```

수정해야 할 부분은 TODO가 좋겠지요 .. !

Comment (rriver2) [reply campair/campair/View/Editor/Detail/OpeningEditorView.swift:42]: 감사합니다 ~

File: campair/campair/Entity/OpeningSection.swift [hunk 4]
```diff
@@ -6,9 +6,13 @@
 //
 
 import Foundation
```
[the remark this answers is not in the document]
Comment (rriver2) [reply campair/campair/Entity/OpeningSection.swift:8]: I deleted import SwiftUI...! (I don't know why SwiftUI is imported)

[the remark this answers is not in the document]
Comment (rriver2) [reply campair/campair/Entity/OpeningSection.swift:8]: thank you young ~

File: campair/campair/Application/ColorExtension.swift (hunk 1 above)
Comment (rriver2) [reply campair/campair/Application/ColorExtension.swift:11]: The color that will be used throughout the app has not been fixed yet. I'm going to add it when it's fixed later. Thank you !

File: campair/campair/Application/ColorExtension.swift [hunk 5]
```diff
@@ -8,12 +8,36 @@
...
+    static let customBlack = Color(#colorLiteral(red: 0.3098039216, green: 0.3098039216, blue: 0.3098039216, alpha: 1))
+    static let customLightGray = Color(#colorLiteral(red: 0.9607843137, green: 0.9607843137, blue: 0.9607843137, alpha: 1))
     static let customCardGray = Color(#colorLiteral(red: 0.9559776187, green: 0.9609488845, blue: 0.956553638, alpha: 1))
-    static let customSelectedHeartRed = Color(#colorLiteral(red: 0.8636257052, green: 0.3744246364, blue: 0.2591798306, alpha: 1))
-    static let customUnselectedHeartGray = Color(#colorLiteral(red: 0.9137255549, green: 0.9137255549, blue: 0.9137255549, alpha: 1))
-    static let customSectionGray = Color(#colorLiteral(red: 0.9725491405, green: 0.9725491405, blue: 0.9725491405, alpha: 1))
-    static let customShareButtonBrown = Color(#colorLiteral(red: 0.3317791522, green: 0.268188715, blue: 0.1943749487, alpha: 1))
+}
+
+extension Color {
```
Comment (sustainable-git) [inline campair/campair/Application/ColorExtension.swift:18]: Good Code.

**Review by sustainable-git — APPROVED** [review]
LGTM

File: campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift (hunk 2 above)
Comment (rriver2) [reply campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift:21]: I made this code because I wanted the content to be drawn on the view only when it wasn't the lastIndex. 
Is there a more neat code? I'm curious.

File: campair/campair/Application/ColorExtension.swift (hunk 5 above)
Comment (rriver2) [reply campair/campair/Application/ColorExtension.swift:18]: thank you smile 🌸

File: campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift (hunk 2 above)
Comment (unnnyong) [reply campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift:21]:
```swift
let lastIndexOfEquipmentContents = equipmentContents.count - 1
if index != lastIndexOfEquipmentContents {
    // ....
}
```

위처럼 값을 정수로 정의해두면, 코드를 읽을 때 lastIndex와 같은지 판단하는구나 ! 라고 바로 읽기 쉬워질거라 생각해요 : )

Comment (rriver2) [reply campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift:21]: Okay, I'll fix it ! Thank you young ><

**Review by Gobans — APPROVED** [review]
LGTM
